trigger:
- main

# required variables:
#   RemoteGit.RepoUrl: 'https://nenoalm:$(AzRepos.Token)@dev.azure.com/nenoALM/DevOps/_git/GitHubSync'
#   RemoteGit.Branch:  'main'
#   AzRepos.Token:      <secret>

steps:
- script: |
    set -x
    git config pull.rebase false
    git remote add target $(RemoteGit.RepoUrl)
    echo git checkout
    git checkout $(Build.SourceBranchName)
    echo git pull
    git pull target $(RemoteGit.Branch) --tags
    echo git push
    git push -u target $(RemoteGit.Branch) --tags
  displayName: 'Push changes to remote Git repository'
