trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  AzRepos.RepoUrl: 'https://nenoalm@dev.azure.com/nenoalm/DevOps/_git/GitHubSync'
  AzRepos.Branch:  'master'

steps:
- script: |
    set -x
    git remote add target $(AzRepos.RepoUrl)
    git checkout $(Build.SourceBranchName)
    git pull target $(AzRepos.Branch) --tags -c http.$REPO_URL.extraHeader="Authorization: Basic $(AzBoards.Token)"
    git push -u target $(AzRepos.Branch) --tags -c http.$REPO_URL.extraHeader="Authorization: Basic $(AzBoards.Token)"
  displayName: 'Push changes to remote Git repository'
